Update README.md
shadow-robot/optoforce pull request #25
Opened 2016-12-12 09:24 UTC by ipa-lth

I added some information I needed to get it running with my setup

2017-01-10 16:12 UTC, toliver requested changes

2017-01-10 16:12 UTC, toliver commented on optoforce/README.md
> +`sudo adduser $USER dialout`.
I would rather use

`sudo usermod -aG $USER dialout`

I think adduser will try to create a new user.

2017-01-10 16:13 UTC, toliver commented
Thanks for your contribution. We will gladly merge, but would you mind to do the small change I suggested?

2017-01-11 08:39 UTC, ipa-lth commented
No problem, I found the "adduser" command somewhat more descriptive, without further knowledge...

You may what to squash-merge both commits to only one.

2021-10-21 15:41 UTC, beatrizleon approved these changes

2021-10-21 15:47 UTC, merged